IP_FILE='ipes.txt'
IP_FILE_EXCLUDED='excludedipes.txt'
LOCAL_PATH='/etc/portscancomparator/'
FLAG_FECHAHORA=`date +%Y%m%dT%H%M`
REPORT_OUTPUT_HTML="$FLAG_FECHAHORA""_psc_report.html"
REPORT="$FLAG_FECHAHORA""_psc_compara_estados.txt"
REPORT_SCAN_BBDD="$FLAG_FECHAHORA""_psc_report.xml"

DNS_SERVER=PUT_YOUR_DNS_HOST_HERE

TARGET_FTP=PUT_YOUR_TARGET_FTP_SERVER_HERE
USER_FTP=PUT_YOUR_USER_FTP_ACCOUNT_HERE
PASS_FTP=PUT_YOUR_PASSWORD_FTP_ACCOUNT_HERE

RESULT2="result2.xml"
RESULT1="result1.xml"



#scan and file dance
nmap --dns-servers $DNS_SERVER -iL "$LOCAL_PATH$IP_FILE" --excludefile "$LOCAL_PATH$IP_FILE_EXCLUDED" -oX "$LOCAL_PATH$RESULT2"
xsltproc "$LOCAL_PATH$RESULT2" -o "$LOCAL_PATH$REPORT_OUTPUT_HTML"
ndiff "$LOCAL_PATH$RESULT1" "$LOCAL_PATH$RESULT2" > "$LOCAL_PATH$REPORT"
cp "$LOCAL_PATH$RESULT2" "$LOCAL_PATH$RESULT1"
rm "$LOCAL_PATH$RESULT2"


#sube por ftp
ftp -n -v $TARGET_FTP << EOT
ascii
user $USER_FTP $PASS_FTP
prompt
cd "Alfresco/Espacios personales de usuario/CMDB/Monitorizacion/PSC"
put "$LOCAL_PATH$REPORT_OUTPUT_HTML" $REPORT_OUTPUT_HTML
put "$LOCAL_PATH$REPORT" $REPORT
put "$LOCAL_PATH$RESULT1" $REPORT_SCAN_BBDD
bye
EOT
